<a href="https://colab.research.google.com/github/riballes/mobile-rag-firewall-/blob/main/experiments/phi_ner/notebooks/01_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PHI NER Fine-tuning on Google Colab

Fine-tune BERT-like models to detect patient **names** and **addresses** in LLM responses, for use in the FW-L2 response firewall.

**Why this exists**: FW-L2 uses regex to catch SSN, phone, email, DOB — but regex can't detect free-form names ("Adah626 Klein929") or addresses ("308 Deckow Union, Pasco"). We fine-tune a small BERT model to fill this gap.

**What this notebook does:**
1. Loads NER training data from Weave (generated from Synthea patient records)
2. Trains 3 model architectures: DistilBERT (66M), BERT (110M), RoBERTa (125M)
3. Evaluates each on a held-out test set via Weave
4. Publishes the best model as a W&B artifact for automatic deployment in FW-L2

**Labels:** `O` (not PHI), `B-NAME` / `I-NAME` (patient name), `B-ADDRESS` / `I-ADDRESS` (address)

**Runtime**: GPU (T4) — Go to Runtime > Change runtime type > GPU

**Estimated time**: ~30-40 minutes for all 3 models

## 1. Setup

Install dependencies and authenticate with W&B.

**W&B API key**: Add `WANDB_API_KEY` to Colab Secrets (key icon in left sidebar) for automatic login. Get your key from [wandb.ai/authorize](https://wandb.ai/authorize).

In [1]:
# Start Time
import time
start_time = time.time()

In [2]:
!pip install -q transformers torch wandb weave accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.5/983.5 kB 27.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 88.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 24.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 157.9 MB/s eta 0:00:00

In [3]:
import wandb
import weave
from google.colab import userdata

WANDB_PROJECT = "mobile-rag-firewall"

# Option A: Use Colab secrets (recommended)
# Go to the key icon in the left sidebar > add WANDB_API_KEY
try:
    wandb_key = userdata.get("WANDB_API_KEY")
    wandb.login(key=wandb_key)
    print("Logged in via Colab secrets")
except Exception:
    # Option B: Manual login — paste your key when prompted
    # Get it from https://wandb.ai/authorize
    wandb.login()

weave.init(WANDB_PROJECT)

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: ricardo-morales-b to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Logged in via Colab secrets

weave: Logged in as Weights & Biases user: ricardo-morales-b.
weave: View Weave data at https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/weave

In [4]:
# Check GPU
import torch
print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    props = torch.cuda.get_device_properties(0)
    mem = getattr(props, "total_memory", None) or getattr(props, "total_mem", 0)
    print(f"Memory: {mem / 1024**3:.1f} GB")

GPU available: True
GPU: Tesla T4
Memory: 14.6 GB

## 2. Load Training Data

Training data is pulled from Weave (`phi-ner-train:latest`, `phi-ner-val:latest`, `phi-ner-test:latest`). These were generated locally by `uv run ner-generate` and published to Weave automatically.

Each example contains:
- `tokens`: list of words (e.g., `["Patient", "Adah626", "Klein929", "lives", "at", "Pasco"]`)
- `ner_tags`: BIO labels per token (e.g., `["O", "B-NAME", "I-NAME", "O", "O", "B-ADDRESS"]`)
- `has_entities`: whether this example contains any NAME/ADDRESS entities

**Data split**: 70% train / 15% val / 15% test

If Weave is unavailable, the cell falls back to manual file upload.

In [5]:
import json
from pathlib import Path
from google.colab import files

DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)

# Pull latest version from Weave (recommended)
try:
    train_dataset = weave.ref("phi-ner-train:latest").get()
    val_dataset = weave.ref("phi-ner-val:latest").get()
    test_dataset = weave.ref("phi-ner-test:latest").get()

    train_data = train_dataset.rows
    val_data = val_dataset.rows
    test_data = test_dataset.rows

    print(f"Loaded latest from Weave:")
    print(f"  Train: {len(train_data)} examples")
    print(f"  Val:   {len(val_data)} examples")
    print(f"  Test:  {len(test_data)} examples")
except Exception as e:
    print(f"Could not load from Weave: {e}")
    print("Upload train.json, val.json, test.json manually")
    uploaded = files.upload()
    with open("train.json") as f: train_data = json.load(f)
    with open("val.json") as f: val_data = json.load(f)
    with open("test.json") as f: test_data = json.load(f)

Loaded latest from Weave:
  Train: 8682 examples
  Val:   1861 examples
  Test:  1861 examples

## 3. Dataset and Model Setup

**PHINERDataset**: Converts our token + BIO tag data into the format HuggingFace Trainer expects. The key challenge is **subword alignment** — BERT tokenizes "Klein929" into `["Klein", "##929"]`, so we need to map our word-level labels to subword tokens:
- First subword of a word gets the word's label
- Continuation subwords (`##929`) get `I-` labels if the word is an entity, or `-100` (ignored in loss) otherwise

**compute_metrics**: Calculates token-level precision, recall, and F1 per entity type (NAME, ADDRESS) during training. This is reported after each epoch in W&B.

**Model configs**: Three architectures compared, each with tuned learning rates and batch sizes optimized for T4 16GB:
| Model | Params | LR | Batch | Why |
|-------|--------|-----|-------|-----|
| DistilBERT | 66M | 5e-5 | 32 | Smallest, fastest — best if task is easy |
| BERT | 110M | 3e-5 | 24 | Standard baseline |
| RoBERTa | 125M | 2e-5 | 24 | Often best for NER — but needs lower LR |

In [6]:
import numpy as np
from torch.utils.data import Dataset as TorchDataset
from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    DataCollatorForTokenClassification,
    EarlyStoppingCallback,
)

# NER label scheme
LABEL_LIST = ["O", "B-NAME", "I-NAME", "B-ADDRESS", "I-ADDRESS"]
LABEL_TO_ID = {l: i for i, l in enumerate(LABEL_LIST)}
ID_TO_LABEL = {i: l for l, i in LABEL_TO_ID.items()}

# Model configurations — optimized for T4 16GB with FP16
MODEL_CONFIGS = {
    "distilbert": {"name": "distilbert-base-uncased", "lr": 5e-5, "epochs": 5, "batch_size": 32},
    "bert": {"name": "bert-base-uncased", "lr": 3e-5, "epochs": 5, "batch_size": 24},
    "roberta": {"name": "roberta-base", "lr": 2e-5, "epochs": 5, "batch_size": 24},
}

print(f"Labels: {LABEL_LIST}")
print(f"Models: {list(MODEL_CONFIGS.keys())}")

Labels: ['O', 'B-NAME', 'I-NAME', 'B-ADDRESS', 'I-ADDRESS']
Models: ['distilbert', 'bert', 'roberta']

In [7]:
class PHINERDataset(TorchDataset):
    """Token classification dataset for PHI NER."""

    def __init__(self, data, tokenizer, max_length=256):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        example = self.data[idx]
        tokens = example["tokens"]
        ner_tags = example["ner_tags"]

        encoding = self.tokenizer(
            tokens, is_split_into_words=True,
            truncation=True, max_length=self.max_length, padding=False,
        )

        word_ids = encoding.word_ids()
        labels = []
        previous_word_id = None

        for word_id in word_ids:
            if word_id is None:
                labels.append(-100)
            elif word_id != previous_word_id:
                label_str = ner_tags[word_id] if word_id < len(ner_tags) else "O"
                labels.append(LABEL_TO_ID.get(label_str, 0))
            else:
                label_str = ner_tags[word_id] if word_id < len(ner_tags) else "O"
                if label_str.startswith("B-"):
                    labels.append(LABEL_TO_ID.get("I-" + label_str[2:], 0))
                elif label_str.startswith("I-"):
                    labels.append(LABEL_TO_ID.get(label_str, 0))
                else:
                    labels.append(-100)
            previous_word_id = word_id

        encoding["labels"] = labels
        return {k: torch.tensor(v) for k, v in encoding.items()}

print("Dataset class ready.")

Dataset class ready.

In [8]:
def compute_metrics(eval_pred):
    """Compute precision, recall, F1 per entity type."""
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=-1)

    true_labels, pred_labels = [], []
    for pred_seq, label_seq in zip(predictions, labels):
        for p, l in zip(pred_seq, label_seq):
            if l != -100:
                true_labels.append(l)
                pred_labels.append(p)

    true_labels = np.array(true_labels)
    pred_labels = np.array(pred_labels)
    metrics = {}

    entity_mask = true_labels != LABEL_TO_ID["O"]
    if entity_mask.sum() > 0:
        entity_correct = (pred_labels[entity_mask] == true_labels[entity_mask]).sum()
        metrics["entity_accuracy"] = float(entity_correct / entity_mask.sum())

    for entity in ["NAME", "ADDRESS"]:
        b_id = LABEL_TO_ID.get(f"B-{entity}", -1)
        i_id = LABEL_TO_ID.get(f"I-{entity}", -1)
        true_entity = np.isin(true_labels, [b_id, i_id])
        pred_entity = np.isin(pred_labels, [b_id, i_id])

        tp = (true_entity & pred_entity).sum()
        fp = (~true_entity & pred_entity).sum()
        fn = (true_entity & ~pred_entity).sum()

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

        metrics[f"precision_{entity}"] = precision
        metrics[f"recall_{entity}"] = recall
        metrics[f"f1_{entity}"] = f1

    entity_f1s = [metrics.get(f"f1_{e}", 0) for e in ["NAME", "ADDRESS"]]
    metrics["f1_macro"] = np.mean(entity_f1s)

    return metrics

print("Metrics function ready.")

Metrics function ready.

## 4. Training Function

`train_model()` handles the full cycle for one model:
1. Initialize W&B run with config + tags
2. Load pre-trained model + tokenizer from HuggingFace
3. Add a token classification head (5 output labels)
4. Train with HuggingFace `Trainer` — evaluates on val set after each epoch
5. Save the best checkpoint (based on `f1_macro`)
6. Log final metrics to W&B

**Key training arguments:**
- `eval_strategy="epoch"` — evaluate after every full pass through the data
- `load_best_model_at_end=True` — keeps the checkpoint with highest F1, not the last one
- `fp16=True` — half-precision training on GPU (2x faster, same accuracy)
- `EarlyStoppingCallback(patience=2)` — stops training if F1 doesn't improve for 2 consecutive epochs
- `dataloader_num_workers=2` — parallel data loading for better GPU utilization
- `report_to="wandb"` — training curves appear in W&B dashboard automatically

In [9]:
def train_model(model_key, train_data, val_data):
    """Train a single model configuration."""
    config = MODEL_CONFIGS[model_key]
    model_name = config["name"]
    output_dir = f"models/{model_key}"

    print(f"\n{'=' * 60}")
    print(f"  Training: {model_key} ({model_name})")
    print(f"  Train: {len(train_data)}, Val: {len(val_data)}")
    print(f"{'=' * 60}")

    wandb.init(
        project=WANDB_PROJECT,
        name=f"phi-ner-{model_key}",
        config={"model": model_name, "model_key": model_key,
                "learning_rate": config["lr"], "epochs": config["epochs"],
                "batch_size": config["batch_size"],
                "train_size": len(train_data), "val_size": len(val_data),
                "labels": LABEL_LIST},
        tags=["phi-ner", model_key, "colab"],
    )

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForTokenClassification.from_pretrained(
        model_name, num_labels=len(LABEL_LIST),
        id2label=ID_TO_LABEL, label2id=LABEL_TO_ID,
    )

    train_dataset = PHINERDataset(train_data, tokenizer)
    val_dataset = PHINERDataset(val_data, tokenizer)
    data_collator = DataCollatorForTokenClassification(tokenizer)

    training_args = TrainingArguments(
        output_dir=output_dir,
        run_name=f"phi-ner-{model_key}",
        report_to="wandb",
        num_train_epochs=config["epochs"],
        per_device_train_batch_size=config["batch_size"],
        per_device_eval_batch_size=config["batch_size"],
        learning_rate=config["lr"],
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        greater_is_better=True,
        save_total_limit=1,
        logging_steps=100,
        fp16=torch.cuda.is_available(),
        dataloader_num_workers=2,
        dataloader_pin_memory=True,
    )

    trainer = Trainer(
        model=model, args=training_args,
        train_dataset=train_dataset, eval_dataset=val_dataset,
        data_collator=data_collator, compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )

    trainer.train()

    # Save best model
    best_dir = f"{output_dir}/best"
    trainer.save_model(best_dir)
    tokenizer.save_pretrained(best_dir)

    # Final evaluation
    eval_results = trainer.evaluate()
    print(f"\n  Final results for {model_key}:")
    for k, v in eval_results.items():
        if isinstance(v, float):
            print(f"    {k}: {v:.4f}")

    wandb.log({f"final/{k}": v for k, v in eval_results.items()})
    wandb.finish()

    return eval_results

print("Training function ready.")

Training function ready.

## 5. Train All 3 Models

Trains DistilBERT, BERT, and RoBERTa sequentially. Early stopping (patience=2) will halt training if F1 plateaus before the max 5 epochs.

After all 3 complete, a comparison table shows F1 macro, F1 per entity type. Look for:
- **F1 macro > 0.99**: The task is well-learned
- **F1 NAME vs F1 ADDRESS**: Names are typically easier (consistent patterns) than addresses (more variation)
- **DistilBERT >= others**: If the smallest model wins, the task doesn't need more capacity

In [10]:
all_results = {}

for model_key in ["distilbert", "bert", "roberta"]:
    results = train_model(model_key, train_data, val_data)
    all_results[model_key] = results

# Print comparison
print(f"\n{'=' * 60}")
print(f"  MODEL COMPARISON (validation set)")
print(f"{'=' * 60}")
print(f"  {'Model':<15} {'F1 Macro':>10} {'F1 NAME':>10} {'F1 ADDR':>10}")
print(f"  {'-'*15} {'-'*10} {'-'*10} {'-'*10}")
for model_key, results in all_results.items():
    f1_macro = results.get("eval_f1_macro", 0)
    f1_name = results.get("eval_f1_NAME", 0)
    f1_addr = results.get("eval_f1_ADDRESS", 0)
    print(f"  {model_key:<15} {f1_macro:>10.4f} {f1_name:>10.4f} {f1_addr:>10.4f}")
print(f"{'=' * 60}")

============================================================
  Training: distilbert (distilbert-base-uncased)
  Train: 8682, Val: 1861
============================================================

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: ricardo-morales-b.
weave: View Weave data at https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/weave
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForTokenClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Final results for distilbert:
    eval_loss: 0.0007
    eval_entity_accuracy: 0.9968
    eval_precision_NAME: 1.0000
    eval_recall_NAME: 1.0000
    eval_f1_NAME: 1.0000
    eval_precision_ADDRESS: 0.9952
    eval_recall_ADDRESS: 0.9937
    eval_f1_ADDRESS: 0.9944
    eval_f1_macro: 0.9972
    eval_runtime: 5.4327
    eval_samples_per_second: 342.5560
    eval_steps_per_second: 10.8600
    epoch: 5.0000

============================================================
  Training: bert (bert-base-uncased)
  Train: 8682, Val: 1861
============================================================

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: ricardo-morales-b.
weave: View Weave data at https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/weave

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Final results for bert:
    eval_loss: 0.0006
    eval_entity_accuracy: 0.9969
    eval_precision_NAME: 1.0000
    eval_recall_NAME: 1.0000
    eval_f1_NAME: 1.0000
    eval_precision_ADDRESS: 0.9961
    eval_recall_ADDRESS: 0.9940
    eval_f1_ADDRESS: 0.9950
    eval_f1_macro: 0.9975
    eval_runtime: 7.2490
    eval_samples_per_second: 256.7250
    eval_steps_per_second: 10.7600
    epoch: 5.0000

============================================================
  Training: roberta (roberta-base)
  Train: 8682, Val: 1861
============================================================

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: ricardo-morales-b.
weave: View Weave data at https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/weave

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForTokenClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
classifier.bias                 | MISSING    |
classifier.weight               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Final results for roberta:
    eval_loss: 0.0008
    eval_entity_accuracy: 0.9969
    eval_precision_NAME: 1.0000
    eval_recall_NAME: 1.0000
    eval_f1_NAME: 1.0000
    eval_precision_ADDRESS: 0.9946
    eval_recall_ADDRESS: 0.9943
    eval_f1_ADDRESS: 0.9945
    eval_f1_macro: 0.9972
    eval_runtime: 7.0908
    eval_samples_per_second: 262.4520
    eval_steps_per_second: 11.0000
    epoch: 5.0000

============================================================
  MODEL COMPARISON (validation set)
============================================================
  Model             F1 Macro    F1 NAME    F1 ADDR
  --------------- ---------- ---------- ----------
  distilbert          0.9972     1.0000     0.9944
  bert                0.9975     1.0000     0.9950
  roberta             0.9972     1.0000     0.9945
============================================================

## 6. Weave Evaluation on Test Set

Runs each trained model through a formal **Weave Evaluation** on the held-out test set. This is different from the training eval:
- Training eval: token-level metrics on the validation set
- Weave eval: entity-level detection rates on the **test set** (never seen during training)

The `NERModel` wraps each trained model as a Weave Model. The `ner_scorer` measures:
- `name_detected`: % of true NAME entities found
- `address_detected`: % of true ADDRESS entities found
- `name_false_positive`: % of non-NAME tokens incorrectly labeled as NAME
- `address_false_positive`: % of non-ADDRESS tokens incorrectly labeled as ADDRESS

Results appear on the W&B Weave dashboard for leaderboard comparison.

In [11]:
from transformers import pipeline as hf_pipeline


class NERModel(weave.Model):
    model_key: str = ""
    model_path: str = ""
    _pipeline: object = None

    def _ensure_loaded(self):
        if self._pipeline is None:
            self._pipeline = hf_pipeline(
                "ner", model=self.model_path, tokenizer=self.model_path,
                aggregation_strategy="simple",
            )

    @weave.op
    def predict(self, tokens: list, ner_tags: list) -> dict:
        self._ensure_loaded()
        text = " ".join(tokens)
        results = self._pipeline(text)

        pred_entities = [
            {"entity": r["entity_group"], "word": r["word"], "score": float(r["score"])}
            for r in results if r["entity_group"] != "O"
        ]

        return {
            "predicted_entities": pred_entities,
            "pred_name_count": sum(1 for e in pred_entities if e["entity"] == "NAME"),
            "pred_address_count": sum(1 for e in pred_entities if e["entity"] == "ADDRESS"),
            "true_name_count": sum(1 for t in ner_tags if t in ("B-NAME", "I-NAME")),
            "true_address_count": sum(1 for t in ner_tags if t in ("B-ADDRESS", "I-ADDRESS")),
            "has_entities": any(t != "O" for t in ner_tags),
        }


@weave.op
def ner_scorer(output: dict) -> dict:
    pred_names = output.get("pred_name_count", 0)
    pred_addrs = output.get("pred_address_count", 0)
    true_names = output.get("true_name_count", 0)
    true_addrs = output.get("true_address_count", 0)

    name_detected = 1.0 if (true_names > 0 and pred_names > 0) else (1.0 if true_names == 0 else 0.0)
    addr_detected = 1.0 if (true_addrs > 0 and pred_addrs > 0) else (1.0 if true_addrs == 0 else 0.0)
    name_fp = 1.0 if (true_names == 0 and pred_names > 0) else 0.0
    addr_fp = 1.0 if (true_addrs == 0 and pred_addrs > 0) else 0.0

    return {
        "name_detected": name_detected,
        "address_detected": addr_detected,
        "name_false_positive": name_fp,
        "address_false_positive": addr_fp,
    }

print("Weave evaluation ready.")

Weave evaluation ready.

In [12]:
# Run Weave evaluation for each model on the test set
test_dataset = weave.Dataset(name="phi-ner-test", rows=test_data)
weave.publish(test_dataset)

for model_key in ["distilbert", "bert", "roberta"]:
    model_path = f"models/{model_key}/best"
    if not Path(model_path).exists():
        print(f"Skipping {model_key} — not trained")
        continue

    print(f"\nEvaluating {model_key} on test set...")

    model = NERModel(
        name=f"phi-ner-{model_key}",
        model_key=model_key,
        model_path=model_path,
    )

    evaluation = weave.Evaluation(
        name=f"ner-eval-{model_key}",
        dataset=test_dataset,
        scorers=[ner_scorer],
        metadata={"model_key": model_key, "source": "colab"},
    )

    results = await evaluation.evaluate(model)
    print(f"  {model_key}: {results}")

weave: 📦 Published to https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/weave/objects/phi-ner-test/versions/BFy1hXzorr0LfqqNE1JI8nEROhzMxLAwHZxHvFD2b88

Evaluating distilbert on test set...

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

weave: 🍩 https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/r/call/019d7feb-b4b2-7eef-8174-176875183ff9

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

weave: Evaluated 1 of 1861 examples
weave: Evaluated 2 of 1861 examples
weave: Evaluated 3 of 1861 examples
weave: Evaluated 4 of 1861 examples
weave: Evaluated 5 of 1861 examples
weave: Evaluated 6 of 1861 examples
weave: Evaluated 7 of 1861 examples
weave: Evaluated 8 of 1861 examples
weave: Evaluated 9 of 1861 examples
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
weave: Evaluated 10 of 1861 examples
weave: Evaluated 11 of 1861 examples
weave: Evaluated 12 of 1861 examples
weave: Evaluated 13 of 1861 examples
weave: Evaluated 14 of 1861 examples
weave: Evaluated 15 of 1861 examples
weave: Evaluated 16 of 1861 examples
weave: Evaluated 17 of 1861 examples
weave: Evaluated 18 of 1861 examples
weave: Evaluated 19 of 1861 examples
weave: Evaluated 20 of 1861 examples
weave: Evaluated 21 of 1861 examples
weave: Evaluated 22 of 1861 examples
weave: Evaluated 23 of 1861 examples
weave: Evaluated 24 of 1861 examples
weave: Evaluated 25 of 1861 examples
weave: Evaluated 26 of 1861 examples
weave: Evaluated 27 of 1861 examples
weave: Evaluated 28 of 1861 examples
weave: Evaluated 29 of 1861 examples
weave: Evaluated 30 of 1861 examples
weave: Evaluated 31 of 1861 examples
weave: Evaluated 32 of 1861 examples
weave: Evaluated 33 of 1861 examples
weave: Evaluated 34 of 1861 examples
weave: Evaluated 35 of 1861 examples
weave: Evaluated 36 of 1861 examples
weave: Evaluated 37 of 1861 examples
weave: Evaluated 38 of 1861 examples
weave: Evaluated 39 of 1861 examples
weave: Evaluated 40 of 1861 examples
weave: Evaluated 41 of 1861 examples
weave: Evaluated 42 of 1861 examples
weave: Evaluated 43 of 1861 examples
weave: Evaluated 44 of 1861 examples
weave: Evaluated 45 of 1861 examples
weave: Evaluated 46 of 1861 examples
weave: Evaluated 47 of 1861 examples
weave: Evaluated 48 of 1861 examples
weave: Evaluated 49 of 1861 examples
weave: Evaluated 50 of 1861 examples
weave: Evaluated 51 of 1861 examples
weave: Evaluated 52 of 1861 examples
weave: Evaluated 53 of 1861 examples
weave: Evaluated 54 of 1861 examples
weave: Evaluated 55 of 1861 examples
weave: Evaluated 56 of 1861 examples
weave: Evaluated 57 of 1861 examples
weave: Evaluated 58 of 1861 examples
weave: Evaluated 59 of 1861 examples
weave: Evaluated 60 of 1861 examples
weave: Evaluated 61 of 1861 examples
weave: Evaluated 62 of 1861 examples
weave: Evaluated 63 of 1861 examples
weave: Evaluated 64 of 1861 examples
weave: Evaluated 65 of 1861 examples
weave: Evaluated 66 of 1861 examples
weave: Evaluated 67 of 1861 examples
weave: Evaluated 68 of 1861 examples
weave: Evaluated 69 of 1861 examples
weave: Evaluated 70 of 1861 examples
weave: Evaluated 71 of 1861 examples
weave: Evaluated 72 of 1861 examples
weave: Evaluated 73 of 1861 examples
weave: Evaluated 74 of 1861 examples
weave: Evaluated 75 of 1861 examples
weave: Evaluated 76 of 1861 examples
weave: Evaluated 77 of 1861 examples
weave: Evaluated 78 of 1861 examples
weave: Evaluated 79 of 1861 examples
weave: Evaluated 80 of 1861 examples
weave: Evaluated 81 of 1861 examples
weave: Evaluated 82 of 1861 examples
weave: Evaluated 83 of 1861 examples
weave: Evaluated 84 of 1861 examples
weave: Evaluated 85 of 1861 examples
weave: Evaluated 86 of 1861 examples
weave: Evaluated 87 of 1861 examples
weave: Evaluated 88 of 1861 examples
weave: Evaluated 89 of 1861 examples
weave: Evaluated 90 of 1861 examples
weave: Evaluated 91 of 1861 examples
weave: Evaluated 92 of 1861 examples
weave: Evaluated 93 of 1861 examples
weave: Evaluated 94 of 1861 examples
weave: Evaluated 95 of 1861 examples
weave: Evaluated 96 of 1861 examples
weave: Evaluated 97 of 1861 examples
weave: Evaluated 98 of 1861 examples
weave: Evaluated 99 of 1861 examples
weave: Evaluated 100 of 1861 examples
weave: Evaluated 101 of 1861 examples
weave: Evaluated 102 of 1861 examples
weave: Evaluated 103 of 1861 examples
weave: Evaluated 104 of 1861 examples
weave: Evaluated 105 of 1861 examples
weave: Evaluated 106 of 1861 examples
weave: Evaluated 107 of 1861 examples
weave: Evaluated 108 of 1861 examples
weave: Evaluated 109 of 1861 examples
weave: Evaluated 110 of 1861 examples
weave: Evaluated 111 of 1861 examples
weave: Evaluated 112 of 1861 examples
weave: Evaluated 113 of 1861 examples
weave: Evaluated 114 of 1861 examples
weave: Evaluated 115 of 1861 examples
weave: Evaluated 116 of 1861 examples
weave: Evaluated 117 of 1861 examples
weave: Evaluated 118 of 1861 examples
weave: Evaluated 119 of 1861 examples
weave: Evaluated 120 of 1861 examples
weave: Evaluated 121 of 1861 examples
weave: Evaluated 122 of 1861 examples
weave: Evaluated 123 of 1861 examples
weave: Evaluated 124 of 1861 examples
weave: Evaluated 125 of 1861 examples
weave: Evaluated 126 of 1861 examples
weave: Evaluated 127 of 1861 examples
weave: Evaluated 128 of 1861 examples
weave: Evaluated 129 of 1861 examples
weave: Evaluated 130 of 1861 examples
weave: Evaluated 131 of 1861 examples
weave: Evaluated 132 of 1861 examples
weave: Evaluated 133 of 1861 examples
weave: Evaluated 134 of 1861 examples
weave: Evaluated 135 of 1861 examples
weave: Evaluated 136 of 1861 examples
weave: Evaluated 137 of 1861 examples
weave: Evaluated 138 of 1861 examples
weave: Evaluated 139 of 1861 examples
weave: Evaluated 140 of 1861 examples
weave: Evaluated 141 of 1861 examples
weave: Evaluated 142 of 1861 examples
weave: Evaluated 143 of 1861 examples
weave: Evaluated 144 of 1861 examples
weave: Evaluated 145 of 1861 examples
weave: Evaluated 146 of 1861 examples
weave: Evaluated 147 of 1861 examples
weave: Evaluated 148 of 1861 examples
weave: Evaluated 149 of 1861 examples
weave: Evaluated 150 of 1861 examples
weave: Evaluated 151 of 1861 examples
weave: Evaluated 152 of 1861 examples
weave: Evaluated 153 of 1861 examples
weave: Evaluated 154 of 1861 examples
weave: Evaluated 155 of 1861 examples
weave: Evaluated 156 of 1861 examples
weave: Evaluated 157 of 1861 examples
weave: Evaluated 158 of 1861 examples
weave: Evaluated 159 of 1861 examples
weave: Evaluated 160 of 1861 examples
weave: Evaluated 161 of 1861 examples
weave: Evaluated 162 of 1861 examples
weave: Evaluated 163 of 1861 examples
weave: Evaluated 164 of 1861 examples
weave: Evaluated 165 of 1861 examples
weave: Evaluated 166 of 1861 examples
weave: Evaluated 167 of 1861 examples
weave: Evaluated 168 of 1861 examples
weave: Evaluated 169 of 1861 examples
weave: Evaluated 170 of 1861 examples
weave: Evaluated 171 of 1861 examples
weave: Evaluated 172 of 1861 examples
weave: Evaluated 173 of 1861 examples
weave: Evaluated 174 of 1861 examples
weave: Evaluated 175 of 1861 examples
weave: Evaluated 176 of 1861 examples
weave: Evaluated 177 of 1861 examples
weave: Evaluated 178 of 1861 examples
weave: Evaluated 179 of 1861 examples
weave: Evaluated 180 of 1861 examples
weave: Evaluated 181 of 1861 examples
weave: Evaluated 182 of 1861 examples
weave: Evaluated 183 of 1861 examples
weave: Evaluated 184 of 1861 examples
weave: Evaluated 185 of 1861 examples
weave: Evaluated 186 of 1861 examples
weave: Evaluated 187 of 1861 examples
weave: Evaluated 188 of 1861 examples
weave: Evaluated 189 of 1861 examples
weave: Evaluated 190 of 1861 examples
weave: Evaluated 191 of 1861 examples
weave: Evaluated 192 of 1861 examples
weave: Evaluated 193 of 1861 examples
weave: Evaluated 194 of 1861 examples
weave: Evaluated 195 of 1861 examples
weave: Evaluated 196 of 1861 examples
weave: Evaluated 197 of 1861 examples
weave: Evaluated 198 of 1861 examples
weave: Evaluated 199 of 1861 examples
weave: Evaluated 200 of 1861 examples
weave: Evaluated 201 of 1861 examples
weave: Evaluated 202 of 1861 examples
weave: Evaluated 203 of 1861 examples
weave: Evaluated 204 of 1861 examples
weave: Evaluated 205 of 1861 examples
weave: Evaluated 206 of 1861 examples
weave: Evaluated 207 of 1861 examples
weave: Evaluated 208 of 1861 examples
weave: Evaluated 209 of 1861 examples
weave: Evaluated 210 of 1861 examples
weave: Evaluated 211 of 1861 examples
weave: Evaluated 212 of 1861 examples
weave: Evaluated 213 of 1861 examples
weave: Evaluated 214 of 1861 examples
weave: Evaluated 215 of 1861 examples
weave: Evaluated 216 of 1861 examples
weave: Evaluated 217 of 1861 examples
weave: Evaluated 218 of 1861 examples
weave: Evaluated 219 of 1861 examples
weave: Evaluated 220 of 1861 examples
weave: Evaluated 221 of 1861 examples
weave: Evaluated 222 of 1861 examples
weave: Evaluated 223 of 1861 examples
weave: Evaluated 224 of 1861 examples
weave: Evaluated 225 of 1861 examples
weave: Evaluated 226 of 1861 examples
weave: Evaluated 227 of 1861 examples
weave: Evaluated 228 of 1861 examples
weave: Evaluated 229 of 1861 examples
weave: Evaluated 230 of 1861 examples
weave: Evaluated 231 of 1861 examples
weave: Evaluated 232 of 1861 examples
weave: Evaluated 233 of 1861 examples
weave: Evaluated 234 of 1861 examples
weave: Evaluated 235 of 1861 examples
weave: Evaluated 236 of 1861 examples
weave: Evaluated 237 of 1861 examples
weave: Evaluated 238 of 1861 examples
weave: Evaluated 239 of 1861 examples
weave: Evaluated 240 of 1861 examples
weave: Evaluated 241 of 1861 examples
weave: Evaluated 242 of 1861 examples
weave: Evaluated 243 of 1861 examples
weave: Evaluated 244 of 1861 examples
weave: Evaluated 245 of 1861 examples
weave: Evaluated 246 of 1861 examples
weave: Evaluated 247 of 1861 examples
weave: Evaluated 248 of 1861 examples
weave: Evaluated 249 of 1861 examples
weave: Evaluated 250 of 1861 examples
weave: Evaluated 251 of 1861 examples
weave: Evaluated 252 of 1861 examples
weave: Evaluated 253 of 1861 examples
weave: Evaluated 254 of 1861 examples
weave: Evaluated 255 of 1861 examples
weave: Evaluated 256 of 1861 examples
weave: Evaluated 257 of 1861 examples
weave: Evaluated 258 of 1861 examples
weave: Evaluated 259 of 1861 examples
weave: Evaluated 260 of 1861 examples
weave: Evaluated 261 of 1861 examples
weave: Evaluated 262 of 1861 examples
weave: Evaluated 263 of 1861 examples
weave: Evaluated 264 of 1861 examples
weave: Evaluated 265 of 1861 examples
weave: Evaluated 266 of 1861 examples
weave: Evaluated 267 of 1861 examples
weave: Evaluated 268 of 1861 examples
weave: Evaluated 269 of 1861 examples
weave: Evaluated 270 of 1861 examples
weave: Evaluated 271 of 1861 examples
weave: Evaluated 272 of 1861 examples
weave: Evaluated 273 of 1861 examples
weave: Evaluated 274 of 1861 examples
weave: Evaluated 275 of 1861 examples
weave: Evaluated 276 of 1861 examples
weave: Evaluated 277 of 1861 examples
weave: Evaluated 278 of 1861 examples
weave: Evaluated 279 of 1861 examples
weave: Evaluated 280 of 1861 examples
weave: Evaluated 281 of 1861 examples
weave: Evaluated 282 of 1861 examples
weave: Evaluated 283 of 1861 examples
weave: Evaluated 284 of 1861 examples
weave: Evaluated 285 of 1861 examples
weave: Evaluated 286 of 1861 examples
weave: Evaluated 287 of 1861 examples
weave: Evaluated 288 of 1861 examples
weave: Evaluated 289 of 1861 examples
weave: Evaluated 290 of 1861 examples
weave: Evaluated 291 of 1861 examples
weave: Evaluated 292 of 1861 examples
weave: Evaluated 293 of 1861 examples
weave: Evaluated 294 of 1861 examples
weave: Evaluated 295 of 1861 examples
weave: Evaluated 296 of 1861 examples
weave: Evaluated 297 of 1861 examples
weave: Evaluated 298 of 1861 examples
weave: Evaluated 299 of 1861 examples
weave: Evaluated 300 of 1861 examples
weave: Evaluated 301 of 1861 examples
weave: Evaluated 302 of 1861 examples
weave: Evaluated 303 of 1861 examples
weave: Evaluated 304 of 1861 examples
weave: Evaluated 305 of 1861 examples
weave: Evaluated 306 of 1861 examples
weave: Evaluated 307 of 1861 examples
weave: Evaluated 308 of 1861 examples
weave: Evaluated 309 of 1861 examples
weave: Evaluated 310 of 1861 examples
weave: Evaluated 311 of 1861 examples
weave: Evaluated 312 of 1861 examples
weave: Evaluated 313 of 1861 examples
weave: Evaluated 314 of 1861 examples
weave: Evaluated 315 of 1861 examples
weave: Evaluated 316 of 1861 examples
weave: Evaluated 317 of 1861 examples
weave: Evaluated 318 of 1861 examples
weave: Evaluated 319 of 1861 examples
weave: Evaluated 320 of 1861 examples
weave: Evaluated 321 of 1861 examples
weave: Evaluated 322 of 1861 examples
weave: Evaluated 323 of 1861 examples
weave: Evaluated 324 of 1861 examples
weave: Evaluated 325 of 1861 examples
weave: Evaluated 326 of 1861 examples
weave: Evaluated 327 of 1861 examples
weave: Evaluated 328 of 1861 examples
weave: Evaluated 329 of 1861 examples
weave: Evaluated 330 of 1861 examples
weave: Evaluated 331 of 1861 examples
weave: Evaluated 332 of 1861 examples
weave: Evaluated 333 of 1861 examples
weave: Evaluated 334 of 1861 examples
weave: Evaluated 335 of 1861 examples
weave: Evaluated 336 of 1861 examples
weave: Evaluated 337 of 1861 examples
weave: Evaluated 338 of 1861 examples
weave: Evaluated 339 of 1861 examples
weave: Evaluated 340 of 1861 examples
weave: Evaluated 341 of 1861 examples
weave: Evaluated 342 of 1861 examples
weave: Evaluated 343 of 1861 examples
weave: Evaluated 344 of 1861 examples
weave: Evaluated 345 of 1861 examples
weave: Evaluated 346 of 1861 examples
weave: Evaluated 347 of 1861 examples
weave: Evaluated 348 of 1861 examples
weave: Evaluated 349 of 1861 examples
weave: Evaluated 350 of 1861 examples
weave: Evaluated 351 of 1861 examples
weave: Evaluated 352 of 1861 examples
weave: Evaluated 353 of 1861 examples
weave: Evaluated 354 of 1861 examples
weave: Evaluated 355 of 1861 examples
weave: Evaluated 356 of 1861 examples
weave: Evaluated 357 of 1861 examples
weave: Evaluated 358 of 1861 examples
weave: Evaluated 359 of 1861 examples
weave: Evaluated 360 of 1861 examples
weave: Evaluated 361 of 1861 examples
weave: Evaluated 362 of 1861 examples
weave: Evaluated 363 of 1861 examples
weave: Evaluated 364 of 1861 examples
weave: Evaluated 365 of 1861 examples
weave: Evaluated 366 of 1861 examples
weave: Evaluated 367 of 1861 examples
weave: Evaluated 368 of 1861 examples
weave: Evaluated 369 of 1861 examples
weave: Evaluated 370 of 1861 examples
weave: Evaluated 371 of 1861 examples
weave: Evaluated 372 of 1861 examples
weave: Evaluated 373 of 1861 examples
weave: Evaluated 374 of 1861 examples
weave: Evaluated 375 of 1861 examples
weave: Evaluated 376 of 1861 examples
weave: Evaluated 377 of 1861 examples
weave: Evaluated 378 of 1861 examples
weave: Evaluated 379 of 1861 examples
weave: Evaluated 380 of 1861 examples
weave: Evaluated 381 of 1861 examples
weave: Evaluated 382 of 1861 examples
weave: Evaluated 383 of 1861 examples
weave: Evaluated 384 of 1861 examples
weave: Evaluated 385 of 1861 examples
weave: Evaluated 386 of 1861 examples
weave: Evaluated 387 of 1861 examples
weave: Evaluated 388 of 1861 examples
weave: Evaluated 389 of 1861 examples
weave: Evaluated 390 of 1861 examples
weave: Evaluated 391 of 1861 examples
weave: Evaluated 392 of 1861 examples
weave: Evaluated 393 of 1861 examples
weave: Evaluated 394 of 1861 examples
weave: Evaluated 395 of 1861 examples
weave: Evaluated 396 of 1861 examples
weave: Evaluated 397 of 1861 examples
weave: Evaluated 398 of 1861 examples
weave: Evaluated 399 of 1861 examples
weave: Evaluated 400 of 1861 examples
weave: Evaluated 401 of 1861 examples
weave: Evaluated 402 of 1861 examples
weave: Evaluated 403 of 1861 examples
weave: Evaluated 404 of 1861 examples
weave: Evaluated 405 of 1861 examples
weave: Evaluated 406 of 1861 examples
weave: Evaluated 407 of 1861 examples
weave: Evaluated 408 of 1861 examples
weave: Evaluated 409 of 1861 examples
weave: Evaluated 410 of 1861 examples
weave: Evaluated 411 of 1861 examples
weave: Evaluated 412 of 1861 examples
weave: Evaluated 413 of 1861 examples
weave: Evaluated 414 of 1861 examples
weave: Evaluated 415 of 1861 examples
weave: Evaluated 416 of 1861 examples
weave: Evaluated 417 of 1861 examples
weave: Evaluated 418 of 1861 examples
weave: Evaluated 419 of 1861 examples
weave: Evaluated 420 of 1861 examples
weave: Evaluated 421 of 1861 examples
weave: Evaluated 422 of 1861 examples
weave: Evaluated 423 of 1861 examples
weave: Evaluated 424 of 1861 examples
weave: Evaluated 425 of 1861 examples
weave: Evaluated 426 of 1861 examples
weave: Evaluated 427 of 1861 examples
weave: Evaluated 428 of 1861 examples
weave: Evaluated 429 of 1861 examples
weave: Evaluated 430 of 1861 examples
weave: Evaluated 431 of 1861 examples
weave: Evaluated 432 of 1861 examples
weave: Evaluated 433 of 1861 examples
weave: Evaluated 434 of 1861 examples
weave: Evaluated 435 of 1861 examples
weave: Evaluated 436 of 1861 examples
weave: Evaluated 437 of 1861 examples
weave: Evaluated 438 of 1861 examples
weave: Evaluated 439 of 1861 examples
weave: Evaluated 440 of 1861 examples
weave: Evaluated 441 of 1861 examples
weave: Evaluated 442 of 1861 examples
weave: Evaluated 443 of 1861 examples
weave: Evaluated 444 of 1861 examples
weave: Evaluated 445 of 1861 examples
weave: Evaluated 446 of 1861 examples
weave: Evaluated 447 of 1861 examples
weave: Evaluated 448 of 1861 examples
weave: Evaluated 449 of 1861 examples
weave: Evaluated 450 of 1861 examples
weave: Evaluated 451 of 1861 examples
weave: Evaluated 452 of 1861 examples
weave: Evaluated 453 of 1861 examples
weave: Evaluated 454 of 1861 examples
weave: Evaluated 455 of 1861 examples
weave: Evaluated 456 of 1861 examples
weave: Evaluated 457 of 1861 examples
weave: Evaluated 458 of 1861 examples
weave: Evaluated 459 of 1861 examples
weave: Evaluated 460 of 1861 examples
weave: Evaluated 461 of 1861 examples
weave: Evaluated 462 of 1861 examples
weave: Evaluated 463 of 1861 examples
weave: Evaluated 464 of 1861 examples
weave: Evaluated 465 of 1861 examples
weave: Evaluated 466 of 1861 examples
weave: Evaluated 467 of 1861 examples
weave: Evaluated 468 of 1861 examples
weave: Evaluated 469 of 1861 examples
weave: Evaluated 470 of 1861 examples
weave: Evaluated 471 of 1861 examples
weave: Evaluated 472 of 1861 examples
weave: Evaluated 473 of 1861 examples
weave: Evaluated 474 of 1861 examples
weave: Evaluated 475 of 1861 examples
weave: Evaluated 476 of 1861 examples
weave: Evaluated 477 of 1861 examples
weave: Evaluated 478 of 1861 examples
weave: Evaluated 479 of 1861 examples
weave: Evaluated 480 of 1861 examples
weave: Evaluated 481 of 1861 examples
weave: Evaluated 482 of 1861 examples
weave: Evaluated 483 of 1861 examples
weave: Evaluated 484 of 1861 examples
weave: Evaluated 485 of 1861 examples
weave: Evaluated 486 of 1861 examples
weave: Evaluated 487 of 1861 examples
weave: Evaluated 488 of 1861 examples
weave: Evaluated 489 of 1861 examples
weave: Evaluated 490 of 1861 examples
weave: Evaluated 491 of 1861 examples
weave: Evaluated 492 of 1861 examples
weave: Evaluated 493 of 1861 examples
weave: Evaluated 494 of 1861 examples
weave: Evaluated 495 of 1861 examples
weave: Evaluated 496 of 1861 examples
weave: Evaluated 497 of 1861 examples
weave: Evaluated 498 of 1861 examples
weave: Evaluated 499 of 1861 examples
weave: Evaluated 500 of 1861 examples
weave: Evaluated 501 of 1861 examples
weave: Evaluated 502 of 1861 examples
weave: Evaluated 503 of 1861 examples
weave: Evaluated 504 of 1861 examples
weave: Evaluated 505 of 1861 examples
weave: Evaluated 506 of 1861 examples
weave: Evaluated 507 of 1861 examples
weave: Evaluated 508 of 1861 examples
weave: Evaluated 509 of 1861 examples
weave: Evaluated 510 of 1861 examples
weave: Evaluated 511 of 1861 examples
weave: Evaluated 512 of 1861 examples
weave: Evaluated 513 of 1861 examples
weave: Evaluated 514 of 1861 examples
weave: Evaluated 515 of 1861 examples
weave: Evaluated 516 of 1861 examples
weave: Evaluated 517 of 1861 examples
weave: Evaluated 518 of 1861 examples
weave: Evaluated 519 of 1861 examples
weave: Evaluated 520 of 1861 examples
weave: Evaluated 521 of 1861 examples
weave: Evaluated 522 of 1861 examples
weave: Evaluated 523 of 1861 examples
weave: Evaluated 524 of 1861 examples
weave: Evaluated 525 of 1861 examples
weave: Evaluated 526 of 1861 examples

  distilbert: {'output': {'pred_name_count': {'mean': 0.27780763030628697}, 'pred_address_count': {'mean': 0.6528747984954326}, 'true_name_count': {'mean': 0.6055883933369156}, 'true_address_count': {'mean': 1.4653412144008597}, 'has_entities': {'true_count': 738, 'true_fraction': 0.39656098871574424}}, 'ner_scorer': {'name_detected': {'mean': 1.0}, 'address_detected': {'mean': 0.99892530897367}, 'name_false_positive': {'mean': 0.0021493820526598604}, 'address_false_positive': {'mean': 0.007522837184309511}}, 'model_latency': {'mean': 1.4928188215078428}}

Evaluating bert on test set...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

weave: 🍩 https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/r/call/019d7fee-6450-734c-9084-83235602039a

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

weave: Evaluated 1 of 1861 examples
weave: Evaluated 2 of 1861 examples
weave: Evaluated 3 of 1861 examples
weave: Evaluated 4 of 1861 examples
weave: Evaluated 5 of 1861 examples
weave: Evaluated 6 of 1861 examples
weave: Evaluated 7 of 1861 examples
weave: Evaluated 8 of 1861 examples
weave: Evaluated 9 of 1861 examples
weave: Evaluated 10 of 1861 examples
weave: Evaluated 11 of 1861 examples
weave: Evaluated 12 of 1861 examples
weave: Evaluated 13 of 1861 examples
weave: Evaluated 14 of 1861 examples
weave: Evaluated 15 of 1861 examples
weave: Evaluated 16 of 1861 examples
weave: Evaluated 17 of 1861 examples
weave: Evaluated 18 of 1861 examples
weave: Evaluated 19 of 1861 examples
weave: Evaluated 20 of 1861 examples
weave: Evaluated 21 of 1861 examples
weave: Evaluated 22 of 1861 examples
weave: Evaluated 23 of 1861 examples
weave: Evaluated 24 of 1861 examples
weave: Evaluated 25 of 1861 examples
weave: Evaluated 26 of 1861 examples
weave: Evaluated 27 of 1861 examples
weave: Evaluated 28 of 1861 examples
weave: Evaluated 29 of 1861 examples
weave: Evaluated 30 of 1861 examples
weave: Evaluated 31 of 1861 examples
weave: Evaluated 32 of 1861 examples
weave: Evaluated 33 of 1861 examples
weave: Evaluated 34 of 1861 examples
weave: Evaluated 35 of 1861 examples
weave: Evaluated 36 of 1861 examples
weave: Evaluated 37 of 1861 examples
weave: Evaluated 38 of 1861 examples
weave: Evaluated 39 of 1861 examples
weave: Evaluated 40 of 1861 examples
weave: Evaluated 41 of 1861 examples
weave: Evaluated 42 of 1861 examples
weave: Evaluated 43 of 1861 examples
weave: Evaluated 44 of 1861 examples
weave: Evaluated 45 of 1861 examples
weave: Evaluated 46 of 1861 examples
weave: Evaluated 47 of 1861 examples
weave: Evaluated 48 of 1861 examples
weave: Evaluated 49 of 1861 examples
weave: Evaluated 50 of 1861 examples
weave: Evaluated 51 of 1861 examples
weave: Evaluated 52 of 1861 examples
weave: Evaluated 53 of 1861 examples
weave: Evaluated 54 of 1861 examples
weave: Evaluated 55 of 1861 examples
weave: Evaluated 56 of 1861 examples
weave: Evaluated 57 of 1861 examples
weave: Evaluated 58 of 1861 examples
weave: Evaluated 59 of 1861 examples
weave: Evaluated 60 of 1861 examples
weave: Evaluated 61 of 1861 examples
weave: Evaluated 62 of 1861 examples
weave: Evaluated 63 of 1861 examples
weave: Evaluated 64 of 1861 examples
weave: Evaluated 65 of 1861 examples
weave: Evaluated 66 of 1861 examples
weave: Evaluated 67 of 1861 examples
weave: Evaluated 68 of 1861 examples
weave: Evaluated 69 of 1861 examples
weave: Evaluated 70 of 1861 examples
weave: Evaluated 71 of 1861 examples
weave: Evaluated 72 of 1861 examples
weave: Evaluated 73 of 1861 examples
weave: Evaluated 74 of 1861 examples
weave: Evaluated 75 of 1861 examples
weave: Evaluated 76 of 1861 examples
weave: Evaluated 77 of 1861 examples
weave: Evaluated 78 of 1861 examples
weave: Evaluated 79 of 1861 examples
weave: Evaluated 80 of 1861 examples
weave: Evaluated 81 of 1861 examples
weave: Evaluated 82 of 1861 examples
weave: Evaluated 83 of 1861 examples
weave: Evaluated 84 of 1861 examples
weave: Evaluated 85 of 1861 examples
weave: Evaluated 86 of 1861 examples
weave: Evaluated 87 of 1861 examples
weave: Evaluated 88 of 1861 examples
weave: Evaluated 89 of 1861 examples
weave: Evaluated 90 of 1861 examples
weave: Evaluated 91 of 1861 examples
weave: Evaluated 92 of 1861 examples
weave: Evaluated 93 of 1861 examples
weave: Evaluated 94 of 1861 examples
weave: Evaluated 95 of 1861 examples
weave: Evaluated 96 of 1861 examples
weave: Evaluated 97 of 1861 examples
weave: Evaluated 98 of 1861 examples
weave: Evaluated 99 of 1861 examples
weave: Evaluated 100 of 1861 examples
weave: Evaluated 101 of 1861 examples
weave: Evaluated 102 of 1861 examples
weave: Evaluated 103 of 1861 examples
weave: Evaluated 104 of 1861 examples
weave: Evaluated 105 of 1861 examples
weave: Evaluated 106 of 1861 examples
weave: Evaluated 107 of 1861 examples
weave: Evaluated 108 of 1861 examples
weave: Evaluated 109 of 1861 examples
weave: Evaluated 110 of 1861 examples
weave: Evaluated 111 of 1861 examples
weave: Evaluated 112 of 1861 examples
weave: Evaluated 113 of 1861 examples
weave: Evaluated 114 of 1861 examples
weave: Evaluated 115 of 1861 examples
weave: Evaluated 116 of 1861 examples
weave: Evaluated 117 of 1861 examples
weave: Evaluated 118 of 1861 examples
weave: Evaluated 119 of 1861 examples
weave: Evaluated 120 of 1861 examples
weave: Evaluated 121 of 1861 examples
weave: Evaluated 122 of 1861 examples
weave: Evaluated 123 of 1861 examples
weave: Evaluated 124 of 1861 examples
weave: Evaluated 125 of 1861 examples
weave: Evaluated 126 of 1861 examples
weave: Evaluated 127 of 1861 examples
weave: Evaluated 128 of 1861 examples
weave: Evaluated 129 of 1861 examples
weave: Evaluated 130 of 1861 examples
weave: Evaluated 131 of 1861 examples
weave: Evaluated 132 of 1861 examples
weave: Evaluated 133 of 1861 examples
weave: Evaluated 134 of 1861 examples
weave: Evaluated 135 of 1861 examples
weave: Evaluated 136 of 1861 examples
weave: Evaluated 137 of 1861 examples
weave: Evaluated 138 of 1861 examples
weave: Evaluated 139 of 1861 examples
weave: Evaluated 140 of 1861 examples
weave: Evaluated 141 of 1861 examples
weave: Evaluated 142 of 1861 examples
weave: Evaluated 143 of 1861 examples
weave: Evaluated 144 of 1861 examples
weave: Evaluated 145 of 1861 examples
weave: Evaluated 146 of 1861 examples
weave: Evaluated 147 of 1861 examples
weave: Evaluated 148 of 1861 examples
weave: Evaluated 149 of 1861 examples
weave: Evaluated 150 of 1861 examples
weave: Evaluated 151 of 1861 examples
weave: Evaluated 152 of 1861 examples
weave: Evaluated 153 of 1861 examples
weave: Evaluated 154 of 1861 examples
weave: Evaluated 155 of 1861 examples
weave: Evaluated 156 of 1861 examples
weave: Evaluated 157 of 1861 examples
weave: Evaluated 158 of 1861 examples
weave: Evaluated 159 of 1861 examples
weave: Evaluated 160 of 1861 examples
weave: Evaluated 161 of 1861 examples
weave: Evaluated 162 of 1861 examples
weave: Evaluated 163 of 1861 examples
weave: Evaluated 164 of 1861 examples
weave: Evaluated 165 of 1861 examples
weave: Evaluated 166 of 1861 examples
weave: Evaluated 167 of 1861 examples
weave: Evaluated 168 of 1861 examples
weave: Evaluated 169 of 1861 examples
weave: Evaluated 170 of 1861 examples
weave: Evaluated 171 of 1861 examples
weave: Evaluated 172 of 1861 examples
weave: Evaluated 173 of 1861 examples
weave: Evaluated 174 of 1861 examples
weave: Evaluated 175 of 1861 examples
weave: Evaluated 176 of 1861 examples
weave: Evaluated 177 of 1861 examples
weave: Evaluated 178 of 1861 examples
weave: Evaluated 179 of 1861 examples
weave: Evaluated 180 of 1861 examples
weave: Evaluated 181 of 1861 examples
weave: Evaluated 182 of 1861 examples
weave: Evaluated 183 of 1861 examples
weave: Evaluated 184 of 1861 examples
weave: Evaluated 185 of 1861 examples
weave: Evaluated 186 of 1861 examples
weave: Evaluated 187 of 1861 examples
weave: Evaluated 188 of 1861 examples
weave: Evaluated 189 of 1861 examples
weave: Evaluated 190 of 1861 examples
weave: Evaluated 191 of 1861 examples
weave: Evaluated 192 of 1861 examples
weave: Evaluated 193 of 1861 examples
weave: Evaluated 194 of 1861 examples
weave: Evaluated 195 of 1861 examples
weave: Evaluated 196 of 1861 examples
weave: Evaluated 197 of 1861 examples
weave: Evaluated 198 of 1861 examples
weave: Evaluated 199 of 1861 examples
weave: Evaluated 200 of 1861 examples
weave: Evaluated 201 of 1861 examples
weave: Evaluated 202 of 1861 examples
weave: Evaluated 203 of 1861 examples
weave: Evaluated 204 of 1861 examples
weave: Evaluated 205 of 1861 examples
weave: Evaluated 206 of 1861 examples
weave: Evaluated 207 of 1861 examples
weave: Evaluated 208 of 1861 examples
weave: Evaluated 209 of 1861 examples
weave: Evaluated 210 of 1861 examples
weave: Evaluated 211 of 1861 examples
weave: Evaluated 212 of 1861 examples
weave: Evaluated 213 of 1861 examples
weave: Evaluated 214 of 1861 examples
weave: Evaluated 215 of 1861 examples
weave: Evaluated 216 of 1861 examples
weave: Evaluated 217 of 1861 examples
weave: Evaluated 218 of 1861 examples
weave: Evaluated 219 of 1861 examples
weave: Evaluated 220 of 1861 examples
weave: Evaluated 221 of 1861 examples
weave: Evaluated 222 of 1861 examples
weave: Evaluated 223 of 1861 examples
weave: Evaluated 224 of 1861 examples
weave: Evaluated 225 of 1861 examples
weave: Evaluated 226 of 1861 examples
weave: Evaluated 227 of 1861 examples
weave: Evaluated 228 of 1861 examples
weave: Evaluated 229 of 1861 examples
weave: Evaluated 230 of 1861 examples
weave: Evaluated 231 of 1861 examples
weave: Evaluated 232 of 1861 examples
weave: Evaluated 233 of 1861 examples
weave: Evaluated 234 of 1861 examples
weave: Evaluated 235 of 1861 examples
weave: Evaluated 236 of 1861 examples
weave: Evaluated 237 of 1861 examples
weave: Evaluated 238 of 1861 examples
weave: Evaluated 239 of 1861 examples
weave: Evaluated 240 of 1861 examples
weave: Evaluated 241 of 1861 examples
weave: Evaluated 242 of 1861 examples
weave: Evaluated 243 of 1861 examples
weave: Evaluated 244 of 1861 examples
weave: Evaluated 245 of 1861 examples
weave: Evaluated 246 of 1861 examples
weave: Evaluated 247 of 1861 examples
weave: Evaluated 248 of 1861 examples
weave: Evaluated 249 of 1861 examples
weave: Evaluated 250 of 1861 examples
weave: Evaluated 251 of 1861 examples
weave: Evaluated 252 of 1861 examples
weave: Evaluated 253 of 1861 examples
weave: Evaluated 254 of 1861 examples
weave: Evaluated 255 of 1861 examples
weave: Evaluated 256 of 1861 examples
weave: Evaluated 257 of 1861 examples
weave: Evaluated 258 of 1861 examples
weave: Evaluated 259 of 1861 examples
weave: Evaluated 260 of 1861 examples
weave: Evaluated 261 of 1861 examples
weave: Evaluated 262 of 1861 examples
weave: Evaluated 263 of 1861 examples
weave: Evaluated 264 of 1861 examples
weave: Evaluated 265 of 1861 examples
weave: Evaluated 266 of 1861 examples
weave: Evaluated 267 of 1861 examples
weave: Evaluated 268 of 1861 examples
weave: Evaluated 269 of 1861 examples
weave: Evaluated 270 of 1861 examples
weave: Evaluated 271 of 1861 examples
weave: Evaluated 272 of 1861 examples
weave: Evaluated 273 of 1861 examples
weave: Evaluated 274 of 1861 examples
weave: Evaluated 275 of 1861 examples
weave: Evaluated 276 of 1861 examples
weave: Evaluated 277 of 1861 examples
weave: Evaluated 278 of 1861 examples
weave: Evaluated 279 of 1861 examples
weave: Evaluated 280 of 1861 examples
weave: Evaluated 281 of 1861 examples
weave: Evaluated 282 of 1861 examples
weave: Evaluated 283 of 1861 examples
weave: Evaluated 284 of 1861 examples
weave: Evaluated 285 of 1861 examples
weave: Evaluated 286 of 1861 examples
weave: Evaluated 287 of 1861 examples
weave: Evaluated 288 of 1861 examples
weave: Evaluated 289 of 1861 examples
weave: Evaluated 290 of 1861 examples
weave: Evaluated 291 of 1861 examples
weave: Evaluated 292 of 1861 examples
weave: Evaluated 293 of 1861 examples
weave: Evaluated 294 of 1861 examples
weave: Evaluated 295 of 1861 examples
weave: Evaluated 296 of 1861 examples
weave: Evaluated 297 of 1861 examples
weave: Evaluated 298 of 1861 examples
weave: Evaluated 299 of 1861 examples
weave: Evaluated 300 of 1861 examples
weave: Evaluated 301 of 1861 examples
weave: Evaluated 302 of 1861 examples
weave: Evaluated 303 of 1861 examples
weave: Evaluated 304 of 1861 examples
weave: Evaluated 305 of 1861 examples
weave: Evaluated 306 of 1861 examples
weave: Evaluated 307 of 1861 examples
weave: Evaluated 308 of 1861 examples
weave: Evaluated 309 of 1861 examples
weave: Evaluated 310 of 1861 examples
weave: Evaluated 311 of 1861 examples
weave: Evaluated 312 of 1861 examples
weave: Evaluated 313 of 1861 examples
weave: Evaluated 314 of 1861 examples
weave: Evaluated 315 of 1861 examples
weave: Evaluated 316 of 1861 examples
weave: Evaluated 317 of 1861 examples
weave: Evaluated 318 of 1861 examples
weave: Evaluated 319 of 1861 examples
weave: Evaluated 320 of 1861 examples
weave: Evaluated 321 of 1861 examples
weave: Evaluated 322 of 1861 examples
weave: Evaluated 323 of 1861 examples
weave: Evaluated 324 of 1861 examples
weave: Evaluated 325 of 1861 examples
weave: Evaluated 326 of 1861 examples
weave: Evaluated 327 of 1861 examples
weave: Evaluated 328 of 1861 examples
weave: Evaluated 329 of 1861 examples
weave: Evaluated 330 of 1861 examples
weave: Evaluated 331 of 1861 examples
weave: Evaluated 332 of 1861 examples
weave: Evaluated 333 of 1861 examples
weave: Evaluated 334 of 1861 examples
weave: Evaluated 335 of 1861 examples
weave: Evaluated 336 of 1861 examples
weave: Evaluated 337 of 1861 examples
weave: Evaluated 338 of 1861 examples
weave: Evaluated 339 of 1861 examples
weave: Evaluated 340 of 1861 examples
weave: Evaluated 341 of 1861 examples
weave: Evaluated 342 of 1861 examples
weave: Evaluated 343 of 1861 examples
weave: Evaluated 344 of 1861 examples
weave: Evaluated 345 of 1861 examples
weave: Evaluated 346 of 1861 examples
weave: Evaluated 347 of 1861 examples
weave: Evaluated 348 of 1861 examples
weave: Evaluated 349 of 1861 examples
weave: Evaluated 350 of 1861 examples
weave: Evaluated 351 of 1861 examples
weave: Evaluated 352 of 1861 examples
weave: Evaluated 353 of 1861 examples
weave: Evaluated 354 of 1861 examples
weave: Evaluated 355 of 1861 examples
weave: Evaluated 356 of 1861 examples
weave: Evaluated 357 of 1861 examples
weave: Evaluated 358 of 1861 examples
weave: Evaluated 359 of 1861 examples
weave: Evaluated 360 of 1861 examples
weave: Evaluated 361 of 1861 examples
weave: Evaluated 362 of 1861 examples
weave: Evaluated 363 of 1861 examples
weave: Evaluated 364 of 1861 examples
weave: Evaluated 365 of 1861 examples
weave: Evaluated 366 of 1861 examples
weave: Evaluated 367 of 1861 examples
weave: Evaluated 368 of 1861 examples
weave: Evaluated 369 of 1861 examples
weave: Evaluated 370 of 1861 examples
weave: Evaluated 371 of 1861 examples
weave: Evaluated 372 of 1861 examples
weave: Evaluated 373 of 1861 examples
weave: Evaluated 374 of 1861 examples
weave: Evaluated 375 of 1861 examples
weave: Evaluated 376 of 1861 examples
weave: Evaluated 377 of 1861 examples
weave: Evaluated 378 of 1861 examples
weave: Evaluated 379 of 1861 examples
weave: Evaluated 380 of 1861 examples
weave: Evaluated 381 of 1861 examples
weave: Evaluated 382 of 1861 examples
weave: Evaluated 383 of 1861 examples
weave: Evaluated 384 of 1861 examples
weave: Evaluated 385 of 1861 examples
weave: Evaluated 386 of 1861 examples
weave: Evaluated 387 of 1861 examples
weave: Evaluated 388 of 1861 examples
weave: Evaluated 389 of 1861 examples
weave: Evaluated 390 of 1861 examples
weave: Evaluated 391 of 1861 examples
weave: Evaluated 392 of 1861 examples
weave: Evaluated 393 of 1861 examples
weave: Evaluated 394 of 1861 examples
weave: Evaluated 395 of 1861 examples
weave: Evaluated 396 of 1861 examples
weave: Evaluated 397 of 1861 examples
weave: Evaluated 398 of 1861 examples
weave: Evaluated 399 of 1861 examples
weave: Evaluated 400 of 1861 examples
weave: Evaluated 401 of 1861 examples
weave: Evaluated 402 of 1861 examples
weave: Evaluated 403 of 1861 examples
weave: Evaluated 404 of 1861 examples
weave: Evaluated 405 of 1861 examples
weave: Evaluated 406 of 1861 examples
weave: Evaluated 407 of 1861 examples
weave: Evaluated 408 of 1861 examples
weave: Evaluated 409 of 1861 examples
weave: Evaluated 410 of 1861 examples
weave: Evaluated 411 of 1861 examples
weave: Evaluated 412 of 1861 examples
weave: Evaluated 413 of 1861 examples
weave: Evaluated 414 of 1861 examples
weave: Evaluated 415 of 1861 examples
weave: Evaluated 416 of 1861 examples
weave: Evaluated 417 of 1861 examples
weave: Evaluated 418 of 1861 examples
weave: Evaluated 419 of 1861 examples
weave: Evaluated 420 of 1861 examples
weave: Evaluated 421 of 1861 examples
weave: Evaluated 422 of 1861 examples
weave: Evaluated 423 of 1861 examples
weave: Evaluated 424 of 1861 examples
weave: Evaluated 425 of 1861 examples
weave: Evaluated 426 of 1861 examples
weave: Evaluated 427 of 1861 examples
weave: Evaluated 428 of 1861 examples
weave: Evaluated 429 of 1861 examples
weave: Evaluated 430 of 1861 examples
weave: Evaluated 431 of 1861 examples
weave: Evaluated 432 of 1861 examples
weave: Evaluated 433 of 1861 examples
weave: Evaluated 434 of 1861 examples
weave: Evaluated 435 of 1861 examples
weave: Evaluated 436 of 1861 examples
weave: Evaluated 437 of 1861 examples
weave: Evaluated 438 of 1861 examples
weave: Evaluated 439 of 1861 examples
weave: Evaluated 440 of 1861 examples
weave: Evaluated 441 of 1861 examples
weave: Evaluated 442 of 1861 examples
weave: Evaluated 443 of 1861 examples
weave: Evaluated 444 of 1861 examples
weave: Evaluated 445 of 1861 examples
weave: Evaluated 446 of 1861 examples
weave: Evaluated 447 of 1861 examples
weave: Evaluated 448 of 1861 examples
weave: Evaluated 449 of 1861 examples
weave: Evaluated 450 of 1861 examples
weave: Evaluated 451 of 1861 examples
weave: Evaluated 452 of 1861 examples
weave: Evaluated 453 of 1861 examples
weave: Evaluated 454 of 1861 examples
weave: Evaluated 455 of 1861 examples
weave: Evaluated 456 of 1861 examples
weave: Evaluated 457 of 1861 examples
weave: Evaluated 458 of 1861 examples
weave: Evaluated 459 of 1861 examples
weave: Evaluated 460 of 1861 examples
weave: Evaluated 461 of 1861 examples
weave: Evaluated 462 of 1861 examples
weave: Evaluated 463 of 1861 examples
weave: Evaluated 464 of 1861 examples
weave: Evaluated 465 of 1861 examples
weave: Evaluated 466 of 1861 examples
weave: Evaluated 467 of 1861 examples
weave: Evaluated 468 of 1861 examples
weave: Evaluated 469 of 1861 examples
weave: Evaluated 470 of 1861 examples
weave: Evaluated 471 of 1861 examples
weave: Evaluated 472 of 1861 examples
weave: Evaluated 473 of 1861 examples
weave: Evaluated 474 of 1861 examples
weave: Evaluated 475 of 1861 examples
weave: Evaluated 476 of 1861 examples
weave: Evaluated 477 of 1861 examples
weave: Evaluated 478 of 1861 examples
weave: Evaluated 479 of 1861 examples
weave: Evaluated 480 of 1861 examples
weave: Evaluated 481 of 1861 examples
weave: Evaluated 482 of 1861 examples
weave: Evaluated 483 of 1861 examples
weave: Evaluated 484 of 1861 examples
weave: Evaluated 485 of 1861 examples
weave: Evaluated 486 of 1861 examples
weave: Evaluated 487 of 1861 examples
weave: Evaluated 488 of 1861 examples
weave: Evaluated 489 of 1861 examples
weave: Evaluated 490 of 1861 examples
weave: Evaluated 491 of 1861 examples
weave: Evaluated 492 of 1861 examples
weave: Evaluated 493 of 1861 examples
weave: Evaluated 494 of 1861 examples
weave: Evaluated 495 of 1861 examples
weave: Evaluated 496 of 1861 examples
weave: Evaluated 497 of 1861 examples
weave: Evaluated 498 of 1861 examples
weave: Evaluated 499 of 1861 examples
weave: Evaluated 500 of 1861 examples
weave: Evaluated 501 of 1861 examples
weave: Evaluated 502 of 1861 examples
weave: Evaluated 503 of 1861 examples
weave: Evaluated 504 of 1861 examples
weave: Evaluated 505 of 1861 examples
weave: Evaluated 506 of 1861 examples
weave: Evaluated 507 of 1861 examples
weave: Evaluated 508 of 1861 examples
weave: Evaluated 509 of 1861 examples
weave: Evaluated 510 of 1861 examples
weave: Evaluated 511 of 1861 examples
weave: Evaluated 512 of 1861 examples
weave: Evaluated 513 of 1861 examples
weave: Evaluated 514 of 1861 examples
weave: Evaluated 515 of 1861 examples
weave: Evaluated 516 of 1861 examples
weave: Evaluated 517 of 1861 examples
weave: Evaluated 518 of 1861 examples
weave: Evaluated 519 of 1861 examples
weave: Evaluated 520 of 1861 examples
weave: Evaluated 521 of 1861 examples
weave: Evaluated 522 of 1861 examples
weave: Evaluated 523 of 1861 examples
weave: Evaluated 524 of 1861 examples
weave: Evaluated 525 of 1861 examples
weave: Evaluated 526 of 1861 examples
weave: Evaluated 527 of 1861 examples
weave: Evaluated 528 of 1861 examples
weave: Evaluated 529 of 1861 examples

  bert: {'output': {'pred_name_count': {'mean': 0.2724341751746373}, 'pred_address_count': {'mean': 0.7098334228909189}, 'true_name_count': {'mean': 0.6055883933369156}, 'true_address_count': {'mean': 1.4653412144008597}, 'has_entities': {'true_count': 738, 'true_fraction': 0.39656098871574424}}, 'ner_scorer': {'name_detected': {'mean': 1.0}, 'address_detected': {'mean': 0.999462654486835}, 'name_false_positive': {'mean': 0.0021493820526598604}, 'address_false_positive': {'mean': 0.025792584631918324}}, 'model_latency': {'mean': 1.6463413082227343}}

Evaluating roberta on test set...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

weave: 🍩 https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/r/call/019d7ff1-5624-7851-85d2-8cce3e81b109

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

weave: Evaluated 1 of 1861 examples
weave: Evaluated 2 of 1861 examples
weave: Evaluated 3 of 1861 examples
weave: Evaluated 4 of 1861 examples
weave: Evaluated 5 of 1861 examples
weave: Evaluated 6 of 1861 examples
weave: Evaluated 7 of 1861 examples
weave: Evaluated 8 of 1861 examples
weave: Evaluated 9 of 1861 examples
weave: Evaluated 10 of 1861 examples
weave: Evaluated 11 of 1861 examples
weave: Evaluated 12 of 1861 examples
weave: Evaluated 13 of 1861 examples
weave: Evaluated 14 of 1861 examples
weave: Evaluated 15 of 1861 examples
weave: Evaluated 16 of 1861 examples
weave: Evaluated 17 of 1861 examples
weave: Evaluated 18 of 1861 examples
weave: Evaluated 19 of 1861 examples
weave: Evaluated 20 of 1861 examples
weave: Evaluated 21 of 1861 examples
weave: Evaluated 22 of 1861 examples
weave: Evaluated 23 of 1861 examples
weave: Evaluated 24 of 1861 examples
weave: Evaluated 25 of 1861 examples
weave: Evaluated 26 of 1861 examples
weave: Evaluated 27 of 1861 examples
weave: Evaluated 28 of 1861 examples
weave: Evaluated 29 of 1861 examples
weave: Evaluated 30 of 1861 examples
weave: Evaluated 31 of 1861 examples
weave: Evaluated 32 of 1861 examples
weave: Evaluated 33 of 1861 examples
weave: Evaluated 34 of 1861 examples
weave: Evaluated 35 of 1861 examples
weave: Evaluated 36 of 1861 examples
weave: Evaluated 37 of 1861 examples
weave: Evaluated 38 of 1861 examples
weave: Evaluated 39 of 1861 examples
weave: Evaluated 40 of 1861 examples
weave: Evaluated 41 of 1861 examples
weave: Evaluated 42 of 1861 examples
weave: Evaluated 43 of 1861 examples
weave: Evaluated 44 of 1861 examples
weave: Evaluated 45 of 1861 examples
weave: Evaluated 46 of 1861 examples
weave: Evaluated 47 of 1861 examples
weave: Evaluated 48 of 1861 examples
weave: Evaluated 49 of 1861 examples
weave: Evaluated 50 of 1861 examples
weave: Evaluated 51 of 1861 examples
weave: Evaluated 52 of 1861 examples
weave: Evaluated 53 of 1861 examples
weave: Evaluated 54 of 1861 examples
weave: Evaluated 55 of 1861 examples
weave: Evaluated 56 of 1861 examples
weave: Evaluated 57 of 1861 examples
weave: Evaluated 58 of 1861 examples
weave: Evaluated 59 of 1861 examples
weave: Evaluated 60 of 1861 examples
weave: Evaluated 61 of 1861 examples
weave: Evaluated 62 of 1861 examples
weave: Evaluated 63 of 1861 examples
weave: Evaluated 64 of 1861 examples
weave: Evaluated 65 of 1861 examples
weave: Evaluated 66 of 1861 examples
weave: Evaluated 67 of 1861 examples
weave: Evaluated 68 of 1861 examples
weave: Evaluated 69 of 1861 examples
weave: Evaluated 70 of 1861 examples
weave: Evaluated 71 of 1861 examples
weave: Evaluated 72 of 1861 examples
weave: Evaluated 73 of 1861 examples
weave: Evaluated 74 of 1861 examples
weave: Evaluated 75 of 1861 examples
weave: Evaluated 76 of 1861 examples
weave: Evaluated 77 of 1861 examples
weave: Evaluated 78 of 1861 examples
weave: Evaluated 79 of 1861 examples
weave: Evaluated 80 of 1861 examples
weave: Evaluated 81 of 1861 examples
weave: Evaluated 82 of 1861 examples
weave: Evaluated 83 of 1861 examples
weave: Evaluated 84 of 1861 examples
weave: Evaluated 85 of 1861 examples
weave: Evaluated 86 of 1861 examples
weave: Evaluated 87 of 1861 examples
weave: Evaluated 88 of 1861 examples
weave: Evaluated 89 of 1861 examples
weave: Evaluated 90 of 1861 examples
weave: Evaluated 91 of 1861 examples
weave: Evaluated 92 of 1861 examples
weave: Evaluated 93 of 1861 examples
weave: Evaluated 94 of 1861 examples
weave: Evaluated 95 of 1861 examples
weave: Evaluated 96 of 1861 examples
weave: Evaluated 97 of 1861 examples
weave: Evaluated 98 of 1861 examples
weave: Evaluated 99 of 1861 examples
weave: Evaluated 100 of 1861 examples
weave: Evaluated 101 of 1861 examples
weave: Evaluated 102 of 1861 examples
weave: Evaluated 103 of 1861 examples
weave: Evaluated 104 of 1861 examples
weave: Evaluated 105 of 1861 examples
weave: Evaluated 106 of 1861 examples
weave: Evaluated 107 of 1861 examples
weave: Evaluated 108 of 1861 examples
weave: Evaluated 109 of 1861 examples
weave: Evaluated 110 of 1861 examples
weave: Evaluated 111 of 1861 examples
weave: Evaluated 112 of 1861 examples
weave: Evaluated 113 of 1861 examples
weave: Evaluated 114 of 1861 examples
weave: Evaluated 115 of 1861 examples
weave: Evaluated 116 of 1861 examples
weave: Evaluated 117 of 1861 examples
weave: Evaluated 118 of 1861 examples
weave: Evaluated 119 of 1861 examples
weave: Evaluated 120 of 1861 examples
weave: Evaluated 121 of 1861 examples
weave: Evaluated 122 of 1861 examples
weave: Evaluated 123 of 1861 examples
weave: Evaluated 124 of 1861 examples
weave: Evaluated 125 of 1861 examples
weave: Evaluated 126 of 1861 examples
weave: Evaluated 127 of 1861 examples
weave: Evaluated 128 of 1861 examples
weave: Evaluated 129 of 1861 examples
weave: Evaluated 130 of 1861 examples
weave: Evaluated 131 of 1861 examples
weave: Evaluated 132 of 1861 examples
weave: Evaluated 133 of 1861 examples
weave: Evaluated 134 of 1861 examples
weave: Evaluated 135 of 1861 examples
weave: Evaluated 136 of 1861 examples
weave: Evaluated 137 of 1861 examples
weave: Evaluated 138 of 1861 examples
weave: Evaluated 139 of 1861 examples
weave: Evaluated 140 of 1861 examples
weave: Evaluated 141 of 1861 examples
weave: Evaluated 142 of 1861 examples
weave: Evaluated 143 of 1861 examples
weave: Evaluated 144 of 1861 examples
weave: Evaluated 145 of 1861 examples
weave: Evaluated 146 of 1861 examples
weave: Evaluated 147 of 1861 examples
weave: Evaluated 148 of 1861 examples
weave: Evaluated 149 of 1861 examples
weave: Evaluated 150 of 1861 examples
weave: Evaluated 151 of 1861 examples
weave: Evaluated 152 of 1861 examples
weave: Evaluated 153 of 1861 examples
weave: Evaluated 154 of 1861 examples
weave: Evaluated 155 of 1861 examples
weave: Evaluated 156 of 1861 examples
weave: Evaluated 157 of 1861 examples
weave: Evaluated 158 of 1861 examples
weave: Evaluated 159 of 1861 examples
weave: Evaluated 160 of 1861 examples
weave: Evaluated 161 of 1861 examples
weave: Evaluated 162 of 1861 examples
weave: Evaluated 163 of 1861 examples
weave: Evaluated 164 of 1861 examples
weave: Evaluated 165 of 1861 examples
weave: Evaluated 166 of 1861 examples
weave: Evaluated 167 of 1861 examples
weave: Evaluated 168 of 1861 examples
weave: Evaluated 169 of 1861 examples
weave: Evaluated 170 of 1861 examples
weave: Evaluated 171 of 1861 examples
weave: Evaluated 172 of 1861 examples
weave: Evaluated 173 of 1861 examples
weave: Evaluated 174 of 1861 examples
weave: Evaluated 175 of 1861 examples
weave: Evaluated 176 of 1861 examples
weave: Evaluated 177 of 1861 examples
weave: Evaluated 178 of 1861 examples
weave: Evaluated 179 of 1861 examples
weave: Evaluated 180 of 1861 examples
weave: Evaluated 181 of 1861 examples
weave: Evaluated 182 of 1861 examples
weave: Evaluated 183 of 1861 examples
weave: Evaluated 184 of 1861 examples
weave: Evaluated 185 of 1861 examples
weave: Evaluated 186 of 1861 examples
weave: Evaluated 187 of 1861 examples
weave: Evaluated 188 of 1861 examples
weave: Evaluated 189 of 1861 examples
weave: Evaluated 190 of 1861 examples
weave: Evaluated 191 of 1861 examples
weave: Evaluated 192 of 1861 examples
weave: Evaluated 193 of 1861 examples
weave: Evaluated 194 of 1861 examples
weave: Evaluated 195 of 1861 examples
weave: Evaluated 196 of 1861 examples
weave: Evaluated 197 of 1861 examples
weave: Evaluated 198 of 1861 examples
weave: Evaluated 199 of 1861 examples
weave: Evaluated 200 of 1861 examples
weave: Evaluated 201 of 1861 examples
weave: Evaluated 202 of 1861 examples
weave: Evaluated 203 of 1861 examples
weave: Evaluated 204 of 1861 examples
weave: Evaluated 205 of 1861 examples
weave: Evaluated 206 of 1861 examples
weave: Evaluated 207 of 1861 examples
weave: Evaluated 208 of 1861 examples
weave: Evaluated 209 of 1861 examples
weave: Evaluated 210 of 1861 examples
weave: Evaluated 211 of 1861 examples
weave: Evaluated 212 of 1861 examples
weave: Evaluated 213 of 1861 examples
weave: Evaluated 214 of 1861 examples
weave: Evaluated 215 of 1861 examples
weave: Evaluated 216 of 1861 examples
weave: Evaluated 217 of 1861 examples
weave: Evaluated 218 of 1861 examples
weave: Evaluated 219 of 1861 examples
weave: Evaluated 220 of 1861 examples
weave: Evaluated 221 of 1861 examples
weave: Evaluated 222 of 1861 examples
weave: Evaluated 223 of 1861 examples
weave: Evaluated 224 of 1861 examples
weave: Evaluated 225 of 1861 examples
weave: Evaluated 226 of 1861 examples
weave: Evaluated 227 of 1861 examples
weave: Evaluated 228 of 1861 examples
weave: Evaluated 229 of 1861 examples
weave: Evaluated 230 of 1861 examples
weave: Evaluated 231 of 1861 examples
weave: Evaluated 232 of 1861 examples
weave: Evaluated 233 of 1861 examples
weave: Evaluated 234 of 1861 examples
weave: Evaluated 235 of 1861 examples
weave: Evaluated 236 of 1861 examples
weave: Evaluated 237 of 1861 examples
weave: Evaluated 238 of 1861 examples
weave: Evaluated 239 of 1861 examples
weave: Evaluated 240 of 1861 examples
weave: Evaluated 241 of 1861 examples
weave: Evaluated 242 of 1861 examples
weave: Evaluated 243 of 1861 examples
weave: Evaluated 244 of 1861 examples
weave: Evaluated 245 of 1861 examples
weave: Evaluated 246 of 1861 examples
weave: Evaluated 247 of 1861 examples
weave: Evaluated 248 of 1861 examples
weave: Evaluated 249 of 1861 examples
weave: Evaluated 250 of 1861 examples
weave: Evaluated 251 of 1861 examples
weave: Evaluated 252 of 1861 examples
weave: Evaluated 253 of 1861 examples
weave: Evaluated 254 of 1861 examples
weave: Evaluated 255 of 1861 examples
weave: Evaluated 256 of 1861 examples
weave: Evaluated 257 of 1861 examples
weave: Evaluated 258 of 1861 examples
weave: Evaluated 259 of 1861 examples
weave: Evaluated 260 of 1861 examples
weave: Evaluated 261 of 1861 examples
weave: Evaluated 262 of 1861 examples
weave: Evaluated 263 of 1861 examples
weave: Evaluated 264 of 1861 examples
weave: Evaluated 265 of 1861 examples
weave: Evaluated 266 of 1861 examples
weave: Evaluated 267 of 1861 examples
weave: Evaluated 268 of 1861 examples
weave: Evaluated 269 of 1861 examples
weave: Evaluated 270 of 1861 examples
weave: Evaluated 271 of 1861 examples
weave: Evaluated 272 of 1861 examples
weave: Evaluated 273 of 1861 examples
weave: Evaluated 274 of 1861 examples
weave: Evaluated 275 of 1861 examples
weave: Evaluated 276 of 1861 examples
weave: Evaluated 277 of 1861 examples
weave: Evaluated 278 of 1861 examples
weave: Evaluated 279 of 1861 examples
weave: Evaluated 280 of 1861 examples
weave: Evaluated 281 of 1861 examples
weave: Evaluated 282 of 1861 examples
weave: Evaluated 283 of 1861 examples
weave: Evaluated 284 of 1861 examples
weave: Evaluated 285 of 1861 examples
weave: Evaluated 286 of 1861 examples
weave: Evaluated 287 of 1861 examples
weave: Evaluated 288 of 1861 examples
weave: Evaluated 289 of 1861 examples
weave: Evaluated 290 of 1861 examples
weave: Evaluated 291 of 1861 examples
weave: Evaluated 292 of 1861 examples
weave: Evaluated 293 of 1861 examples
weave: Evaluated 294 of 1861 examples
weave: Evaluated 295 of 1861 examples
weave: Evaluated 296 of 1861 examples
weave: Evaluated 297 of 1861 examples
weave: Evaluated 298 of 1861 examples
weave: Evaluated 299 of 1861 examples
weave: Evaluated 300 of 1861 examples
weave: Evaluated 301 of 1861 examples
weave: Evaluated 302 of 1861 examples
weave: Evaluated 303 of 1861 examples
weave: Evaluated 304 of 1861 examples
weave: Evaluated 305 of 1861 examples
weave: Evaluated 306 of 1861 examples
weave: Evaluated 307 of 1861 examples
weave: Evaluated 308 of 1861 examples
weave: Evaluated 309 of 1861 examples
weave: Evaluated 310 of 1861 examples
weave: Evaluated 311 of 1861 examples
weave: Evaluated 312 of 1861 examples
weave: Evaluated 313 of 1861 examples
weave: Evaluated 314 of 1861 examples
weave: Evaluated 315 of 1861 examples
weave: Evaluated 316 of 1861 examples
weave: Evaluated 317 of 1861 examples
weave: Evaluated 318 of 1861 examples
weave: Evaluated 319 of 1861 examples
weave: Evaluated 320 of 1861 examples
weave: Evaluated 321 of 1861 examples
weave: Evaluated 322 of 1861 examples
weave: Evaluated 323 of 1861 examples
weave: Evaluated 324 of 1861 examples
weave: Evaluated 325 of 1861 examples
weave: Evaluated 326 of 1861 examples
weave: Evaluated 327 of 1861 examples
weave: Evaluated 328 of 1861 examples
weave: Evaluated 329 of 1861 examples
weave: Evaluated 330 of 1861 examples
weave: Evaluated 331 of 1861 examples
weave: Evaluated 332 of 1861 examples
weave: Evaluated 333 of 1861 examples
weave: Evaluated 334 of 1861 examples
weave: Evaluated 335 of 1861 examples
weave: Evaluated 336 of 1861 examples
weave: Evaluated 337 of 1861 examples
weave: Evaluated 338 of 1861 examples
weave: Evaluated 339 of 1861 examples
weave: Evaluated 340 of 1861 examples
weave: Evaluated 341 of 1861 examples
weave: Evaluated 342 of 1861 examples
weave: Evaluated 343 of 1861 examples
weave: Evaluated 344 of 1861 examples
weave: Evaluated 345 of 1861 examples
weave: Evaluated 346 of 1861 examples
weave: Evaluated 347 of 1861 examples
weave: Evaluated 348 of 1861 examples
weave: Evaluated 349 of 1861 examples
weave: Evaluated 350 of 1861 examples
weave: Evaluated 351 of 1861 examples
weave: Evaluated 352 of 1861 examples
weave: Evaluated 353 of 1861 examples
weave: Evaluated 354 of 1861 examples
weave: Evaluated 355 of 1861 examples
weave: Evaluated 356 of 1861 examples
weave: Evaluated 357 of 1861 examples
weave: Evaluated 358 of 1861 examples
weave: Evaluated 359 of 1861 examples
weave: Evaluated 360 of 1861 examples
weave: Evaluated 361 of 1861 examples
weave: Evaluated 362 of 1861 examples
weave: Evaluated 363 of 1861 examples
weave: Evaluated 364 of 1861 examples
weave: Evaluated 365 of 1861 examples
weave: Evaluated 366 of 1861 examples
weave: Evaluated 367 of 1861 examples
weave: Evaluated 368 of 1861 examples
weave: Evaluated 369 of 1861 examples
weave: Evaluated 370 of 1861 examples
weave: Evaluated 371 of 1861 examples
weave: Evaluated 372 of 1861 examples
weave: Evaluated 373 of 1861 examples
weave: Evaluated 374 of 1861 examples
weave: Evaluated 375 of 1861 examples
weave: Evaluated 376 of 1861 examples
weave: Evaluated 377 of 1861 examples
weave: Evaluated 378 of 1861 examples
weave: Evaluated 379 of 1861 examples
weave: Evaluated 380 of 1861 examples
weave: Evaluated 381 of 1861 examples
weave: Evaluated 382 of 1861 examples
weave: Evaluated 383 of 1861 examples
weave: Evaluated 384 of 1861 examples
weave: Evaluated 385 of 1861 examples
weave: Evaluated 386 of 1861 examples
weave: Evaluated 387 of 1861 examples
weave: Evaluated 388 of 1861 examples
weave: Evaluated 389 of 1861 examples
weave: Evaluated 390 of 1861 examples
weave: Evaluated 391 of 1861 examples
weave: Evaluated 392 of 1861 examples
weave: Evaluated 393 of 1861 examples
weave: Evaluated 394 of 1861 examples
weave: Evaluated 395 of 1861 examples
weave: Evaluated 396 of 1861 examples
weave: Evaluated 397 of 1861 examples
weave: Evaluated 398 of 1861 examples
weave: Evaluated 399 of 1861 examples
weave: Evaluated 400 of 1861 examples
weave: Evaluated 401 of 1861 examples
weave: Evaluated 402 of 1861 examples
weave: Evaluated 403 of 1861 examples
weave: Evaluated 404 of 1861 examples
weave: Evaluated 405 of 1861 examples
weave: Evaluated 406 of 1861 examples
weave: Evaluated 407 of 1861 examples
weave: Evaluated 408 of 1861 examples
weave: Evaluated 409 of 1861 examples
weave: Evaluated 410 of 1861 examples
weave: Evaluated 411 of 1861 examples
weave: Evaluated 412 of 1861 examples
weave: Evaluated 413 of 1861 examples
weave: Evaluated 414 of 1861 examples
weave: Evaluated 415 of 1861 examples
weave: Evaluated 416 of 1861 examples
weave: Evaluated 417 of 1861 examples
weave: Evaluated 418 of 1861 examples
weave: Evaluated 419 of 1861 examples
weave: Evaluated 420 of 1861 examples
weave: Evaluated 421 of 1861 examples
weave: Evaluated 422 of 1861 examples
weave: Evaluated 423 of 1861 examples
weave: Evaluated 424 of 1861 examples
weave: Evaluated 425 of 1861 examples
weave: Evaluated 426 of 1861 examples
weave: Evaluated 427 of 1861 examples
weave: Evaluated 428 of 1861 examples
weave: Evaluated 429 of 1861 examples
weave: Evaluated 430 of 1861 examples
weave: Evaluated 431 of 1861 examples
weave: Evaluated 432 of 1861 examples
weave: Evaluated 433 of 1861 examples
weave: Evaluated 434 of 1861 examples
weave: Evaluated 435 of 1861 examples
weave: Evaluated 436 of 1861 examples
weave: Evaluated 437 of 1861 examples
weave: Evaluated 438 of 1861 examples
weave: Evaluated 439 of 1861 examples
weave: Evaluated 440 of 1861 examples
weave: Evaluated 441 of 1861 examples
weave: Evaluated 442 of 1861 examples
weave: Evaluated 443 of 1861 examples
weave: Evaluated 444 of 1861 examples
weave: Evaluated 445 of 1861 examples
weave: Evaluated 446 of 1861 examples
weave: Evaluated 447 of 1861 examples
weave: Evaluated 448 of 1861 examples
weave: Evaluated 449 of 1861 examples
weave: Evaluated 450 of 1861 examples
weave: Evaluated 451 of 1861 examples
weave: Evaluated 452 of 1861 examples
weave: Evaluated 453 of 1861 examples
weave: Evaluated 454 of 1861 examples
weave: Evaluated 455 of 1861 examples
weave: Evaluated 456 of 1861 examples
weave: Evaluated 457 of 1861 examples
weave: Evaluated 458 of 1861 examples
weave: Evaluated 459 of 1861 examples
weave: Evaluated 460 of 1861 examples
weave: Evaluated 461 of 1861 examples
weave: Evaluated 462 of 1861 examples
weave: Evaluated 463 of 1861 examples
weave: Evaluated 464 of 1861 examples
weave: Evaluated 465 of 1861 examples
weave: Evaluated 466 of 1861 examples
weave: Evaluated 467 of 1861 examples
weave: Evaluated 468 of 1861 examples
weave: Evaluated 469 of 1861 examples
weave: Evaluated 470 of 1861 examples
weave: Evaluated 471 of 1861 examples
weave: Evaluated 472 of 1861 examples
weave: Evaluated 473 of 1861 examples
weave: Evaluated 474 of 1861 examples
weave: Evaluated 475 of 1861 examples
weave: Evaluated 476 of 1861 examples
weave: Evaluated 477 of 1861 examples
weave: Evaluated 478 of 1861 examples
weave: Evaluated 479 of 1861 examples
weave: Evaluated 480 of 1861 examples
weave: Evaluated 481 of 1861 examples
weave: Evaluated 482 of 1861 examples
weave: Evaluated 483 of 1861 examples
weave: Evaluated 484 of 1861 examples
weave: Evaluated 485 of 1861 examples
weave: Evaluated 486 of 1861 examples
weave: Evaluated 487 of 1861 examples
weave: Evaluated 488 of 1861 examples
weave: Evaluated 489 of 1861 examples
weave: Evaluated 490 of 1861 examples
weave: Evaluated 491 of 1861 examples
weave: Evaluated 492 of 1861 examples
weave: Evaluated 493 of 1861 examples
weave: Evaluated 494 of 1861 examples
weave: Evaluated 495 of 1861 examples
weave: Evaluated 496 of 1861 examples
weave: Evaluated 497 of 1861 examples
weave: Evaluated 498 of 1861 examples
weave: Evaluated 499 of 1861 examples
weave: Evaluated 500 of 1861 examples
weave: Evaluated 501 of 1861 examples
weave: Evaluated 502 of 1861 examples
weave: Evaluated 503 of 1861 examples
weave: Evaluated 504 of 1861 examples
weave: Evaluated 505 of 1861 examples
weave: Evaluated 506 of 1861 examples
weave: Evaluated 507 of 1861 examples
weave: Evaluated 508 of 1861 examples
weave: Evaluated 509 of 1861 examples
weave: Evaluated 510 of 1861 examples
weave: Evaluated 511 of 1861 examples
weave: Evaluated 512 of 1861 examples
weave: Evaluated 513 of 1861 examples
weave: Evaluated 514 of 1861 examples
weave: Evaluated 515 of 1861 examples
weave: Evaluated 516 of 1861 examples
weave: Evaluated 517 of 1861 examples
weave: Evaluated 518 of 1861 examples
weave: Evaluated 519 of 1861 examples
weave: Evaluated 520 of 1861 examples
weave: Evaluated 521 of 1861 examples
weave: Evaluated 522 of 1861 examples
weave: Evaluated 523 of 1861 examples
weave: Evaluated 524 of 1861 examples
weave: Evaluated 525 of 1861 examples
weave: Evaluated 526 of 1861 examples
weave: Evaluated 527 of 1861 examples
weave: Evaluated 528 of 1861 examples
weave: Evaluated 529 of 1861 examples

  roberta: {'output': {'pred_name_count': {'mean': 0.29607737775389575}, 'pred_address_count': {'mean': 1.3036002149382053}, 'true_name_count': {'mean': 0.6055883933369156}, 'true_address_count': {'mean': 1.4653412144008597}, 'has_entities': {'true_count': 738, 'true_fraction': 0.39656098871574424}}, 'ner_scorer': {'name_detected': {'mean': 1.0}, 'address_detected': {'mean': 0.9978506179473401}, 'name_false_positive': {'mean': 0.0010746910263299302}, 'address_false_positive': {'mean': 0.06663084363245567}}, 'model_latency': {'mean': 1.7263512634449527}}

## 7. Publish Best Model

Publish the best model to W&B as a model artifact (`phi-ner-model`). FW-L2 in the backend will pull it automatically via `run.use_artifact("phi-ner-model:latest")` — no manual download or file transfer needed.

**Choose the best model** by changing `BEST_MODEL` based on the comparison table from Step 5. Consider:
- **Highest F1 macro**: Best overall accuracy
- **Lowest false positive rate**: Least over-redaction of clean text
- **Smallest size** (DistilBERT): Fastest inference, smallest footprint

If you want a local copy too, uncomment the zip download lines at the bottom.

In [13]:
import shutil
import os

# Choose the best model based on results above
BEST_MODEL = "distilbert"  # Change this based on results
best_model_path = f"models/{BEST_MODEL}/best"

# ── Publish as W&B Model Artifact ──
# This makes the model available as a proper artifact that can be downloaded
# and loaded with AutoModelForTokenClassification.from_pretrained()

run = wandb.init(
    project=WANDB_PROJECT,
    name=f"publish-phi-ner-{BEST_MODEL}",
    job_type="publish-model",
    tags=["phi-ner", BEST_MODEL, "publish"],
)

artifact = wandb.Artifact(
    name="phi-ner-model",
    type="model",
    description=f"Best PHI NER model ({BEST_MODEL}) for detecting NAME and ADDRESS entities",
    metadata={"model_key": BEST_MODEL, "base_model": MODEL_CONFIGS[BEST_MODEL]["name"]},
)
artifact.add_dir(best_model_path)
run.log_artifact(artifact)
run.finish()

print(f"Published model artifact: phi-ner-model:latest")
print(f"Download with:")
print(f"  run = wandb.init(project='{WANDB_PROJECT}')")
print(f"  artifact = run.use_artifact('phi-ner-model:latest')")
print(f"  model_dir = artifact.download()")
print(f"  model = AutoModelForTokenClassification.from_pretrained(model_dir)")

# ── Optional: Download zip for local use ──
# Uncomment the lines below if you also want a local copy
# shutil.make_archive(f"phi-ner-{BEST_MODEL}", "zip", best_model_path)
# files.download(f"phi-ner-{BEST_MODEL}.zip")

wandb: Initializing weave.

Output()

weave: Flushing 3 pending tasks...

weave: Logged in as Weights & Biases user: ricardo-morales-b.
weave: View Weave data at https://wandb.ai/ricardo-morales-b/mobile-rag-firewall/weave
wandb: Adding directory to artifact (models/distilbert/best)... Done. 0.7s

Published model artifact: phi-ner-model:latest
Download with:
  run = wandb.init(project='mobile-rag-firewall')
  artifact = run.use_artifact('phi-ner-model:latest')
  model_dir = artifact.download()
  model = AutoModelForTokenClassification.from_pretrained(model_dir)

In [14]:
# End Time
end_time = time.time()
total_time = end_time - start_time

# Convert to minutes and seconds
mins, secs = divmod(total_time, 60)
print(f"Total Notebook Execution Time: {int(mins)}m {int(secs)}s")

Total Notebook Execution Time: 35m 20s